theme: Minima
#remote_theme: mmistakes/jekyll-theme-basically-basic

title: Zuos Weblog

minima:
  skin: auto
  show_excerpts: true
  hide_site_feed_link: true

sass:
  quiet_deps: true
  silence_deprecations: [import]

